apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${VOLUME_NAME_DATA}-pv
  namespace: ${P_K8S_NAMESPACE}
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: "${VOLUME_DIR_DATA}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${VOLUME_NAME_DATA}-pvc
  namespace: ${P_K8S_NAMESPACE}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: "${VOLUME_NAME_DATA}-pv"
  storageClassName: local-storage